### PR TITLE
allow "to" to be an array of email addresses

### PR DESCRIPTION
**Pull request by shaunc**
Fix for https://github.com/bcoe/nodemailer-mock-transport/issues/4

### CODE REVIEW

**Comment by shaunc** [comment]
... also will catch and correctly pass to callback errors resulting from "to" or element of "to" not being strings.

**Comment by bcoe** [comment]
Hey @shaunc sorry that I dropped this pull request on the floor.

**Comment by bcoe** [comment]
@shaunc see: https://github.com/bcoe/nodemailer-mock-transport/blob/master/CHANGELOG.md#130-2016-06-03

**Comment by shaunc** [comment]
Great! thanks! :)

**Pull request merged**
